### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by manulera** [pombase/canto_tutorial#1]
Hi @ValWood, I have a question about the physical interactions in Canto for the documentation.

<img width="642" alt="Screenshot 2023-08-30 at 18 06 35" src="https://github.com/pombase/canto_tutorial/assets/22526102/c953d7da-358e-4efa-9747-1018da8256aa">

Does it ever matter the order in which the genes are listed? My intuition is that:
    * For `affinity captures`, the first one should be the bait and the other
    * For `Protein-RNA (binds to RNA)`, the first one should be the protein gene, and the second one the RNA one.
    * For `Protein-Peptide`, the first one should be the full protein, the second one the peptide.

**Comment by manulera** [comment]
Another question, that I am adding to a section `More about expression level and edge cases`:

> PomBase does not capture the difference between strains expressing an allele from a plasmid or the native locus in phenotype annotations.  Similarly, we do not have a way to capture the fact that the control of an experiments is over-expressing the wild-type allele. Therefore, if both the wild-type (control) and mutant allele are over-expressed / knocked-down, ???

What do we say here?

**Comment by ValWood** [comment]
>Therefore, if both the wild-type (control) and mutant allele are over-expressed / knocked-down, 

I'm not sure. Yesterday I made such and annotation
overexpressed mutant compared to OEX WT control. I 
made the mutant overexpresses  the assumption being that the WT control is also Overexpressed.
This is never stated explicitly in the curation  though that we are not comparing to WT with normal expression.

**Comment by ValWood** [comment]
The interactions are directional
https://wiki.thebiogrid.org/doku.php/experimental_systems
but the direction should be explicit in the text in parentheses (i.e "affinity captures"  was supposed imply that a captures b

Maybe this is not clear enough?

**Comment by manulera** [comment]
Ok, that should be enough for me to write it
